/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View_Thuoc_Tinh;

import Model.Imei;
import Repository.CPURepository;
import Repository.ImeiDaBanRepository;
import Repository.ImeiRepository;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import raven.application.form.other.SanPham;

/**
 *
 * @author nothank
 */
public class ImeiView extends javax.swing.JFrame {

    private ImeiRepository repo = new ImeiRepository();
    private ImeiDaBanRepository repoDB = new ImeiDaBanRepository();
    private DefaultTableModel dtm;
    private ArrayList<ImeiView> arrC = new ArrayList<>();
    private int page = 1;
    private int limit = 20;

    /**
     * Creates new form CPU
     */
    public ImeiView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.showImei(repo.getAll(page, limit));
        this.showImeiDB(repoDB.getAll(page, limit));
        this.showName();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Ngăn cửa sổ tự động đóng
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Hiển thị hộp thoại xác nhận khi đóng
                int option = JOptionPane.showConfirmDialog(null, "Bạn có muốn quay về trang chủ?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    goToHomePage(); // Quay về trang chính
                }
            }
        });
    }

    private void showName() {
        cbbTenSanPham.removeAllItems();
        for (Imei dl : repo.getNames()) {
            cbbTenSanPham.addItem(dl.getTen_San_Pham()); // Thêm Ten_San_Pham vào ComboBox
        }
    }

    private void showImei(ArrayList<Model.Imei> arr) {
        dtm = (DefaultTableModel) this.tblIemi.getModel();
        dtm.setRowCount(0);
        for (Model.Imei imei : arr) {
            Object[] row = {
                imei.getID_Imei(),
                imei.getMa_Imei(),
                imei.getTrang_thai() == 1 ? "Còn Hàng" : "Đã Bán",
                imei.getMa_San_Pham(),
                imei.getTen_San_Pham()
            };
            dtm.addRow(row);
        }
    }

    private void showImeiDB(ArrayList<Model.ImeiDaBan> arr) {
        dtm = (DefaultTableModel) this.tblIemi1.getModel();
        dtm.setRowCount(0);
        for (Model.ImeiDaBan imei : arr) {
            Object[] row = {
                imei.getID_Imei_Da_Ban(),
                imei.getMa_Imei_Da_Ban(),
                imei.getID_HDCT(),};
            dtm.addRow(row);
        }
    }

    private void goToHomePage() {
        // Logic để quay về trang chính
        SanPham sanPham = new SanPham(); // Tạo đối tượng trang chính
        sanPham.setVisible(true); // Hiển thị trang chính
        this.dispose(); // Đóng cửa sổ hiện tại
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIemi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID_Imei = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImei = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        cbbTenSanPham = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnBack1 = new javax.swing.JButton();
        lblPage1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID_Imei1 = new javax.swing.JTextField();
        txtIDHDCT = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtImei1 = new javax.swing.JTextField();
        txtSearch1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIemi1 = new javax.swing.JTable();
        btnNext1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSearch.setText("Clear");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Trạng Thái");

        tblIemi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Imei", "Imei", "Trạng Thái", "Mã Sản Phẩm", "Tên Sản Phẩm"
            }
        ));
        tblIemi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIemiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIemi);

        jLabel4.setText("Mã Sản Phẩm");

        jLabel1.setText("ID_Imei");

        jLabel5.setText("Tên Sản Phẩm");

        jLabel2.setText("Imei");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Next.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPage.setText("1");

        cbbTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTenSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(4, 4, 4)
                        .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnNext))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 173, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSanPham)
                            .addComponent(txtTrangThai)
                            .addComponent(txtImei)
                            .addComponent(txtID_Imei, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbbTenSanPham, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID_Imei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext)
                    .addComponent(btnSearch))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Imei", jPanel1);

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        lblPage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPage1.setText("1");

        jLabel7.setText("ID_Imei_Đã_Bán");

        jLabel8.setText("ID Hóa Đơn Chi Tiết");

        btnSearch1.setText("Clear");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Imei Đã Bán");

        tblIemi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID_Imei_Đã_Bán", "Imei Đã Bán", "ID Hóa Đơn Chi Tiết"
            }
        ));
        tblIemi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIemi1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblIemi1);

        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Next.png"))); // NOI18N
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBack1)
                        .addGap(4, 4, 4)
                        .addComponent(lblPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnNext1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(0, 159, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIDHDCT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImei1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID_Imei1))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID_Imei1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtImei1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnSearch1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack1)
                    .addComponent(lblPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext1))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ImeDaBan", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.page--;
        this.showImei(repo.getAll(page, limit));
        this.lblPage.setText(this.page + "");

        // Nếu ở trang đầu tiên, vô hiệu hóa nút back, nếu không, kích hoạt nút next
        if (this.page == 1) {
            this.btnBack.setEnabled(false);
        } else {
            this.btnBack.setEnabled(true);
        }

        // Kích hoạt nút next khi không ở trang cuối
        if (this.page < 5) { // Giả sử trang cuối là 5
            this.btnNext.setEnabled(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.page++;
        this.showImei(repo.getAll(page, limit));
        this.lblPage.setText(this.page + "");

        // Kích hoạt nút back khi không ở trang đầu
        if (this.page > 1) {
            this.btnBack.setEnabled(true);
        }

        // Vô hiệu hóa nút next khi đến trang cuối
        if (this.page == 5) { // Giả sử trang cuối là 5
            this.btnNext.setEnabled(false);
        } else {
            this.btnNext.setEnabled(true);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.page--;
        this.showImeiDB(repoDB.getAll(page, limit));
        this.lblPage1.setText(this.page + "");

        // Vô hiệu hóa nút back khi ở trang đầu tiên
        if (this.page == 1) {
            this.btnBack1.setEnabled(false);
        } else {
            this.btnBack1.setEnabled(true);
        }

        // Kích hoạt nút next nếu không ở trang cuối
        if (this.page < 5) { // Giả sử trang cuối là 5
            this.btnNext1.setEnabled(true);
        }
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
        this.page++;
        this.showImeiDB(repoDB.getAll(page, limit));
        this.lblPage1.setText(this.page + "");

        // Kích hoạt nút back khi không ở trang đầu
        if (this.page > 1) {
            this.btnBack1.setEnabled(true);
        }

        // Vô hiệu hóa nút next khi đến trang cuối
        if (this.page == 5) { // Giả sử trang cuối là 5
            this.btnNext1.setEnabled(false);
        } else {
            this.btnNext1.setEnabled(true);
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void tblIemiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIemiMouseClicked
        // TODO add your handling code here:
        int row = tblIemi.getSelectedRow();
        if (row == -1) {
            return;
        }
        String IDImei = tblIemi.getValueAt(row, 0).toString();
        String Imei = tblIemi.getValueAt(row, 1).toString();
        String TrangThai = tblIemi.getValueAt(row, 2).toString();
        String MaSp = tblIemi.getValueAt(row, 3).toString();
        String TenSp = tblIemi.getValueAt(row, 4).toString();

        txtID_Imei.setText(IDImei);
        txtImei.setText(Imei);
        txtTrangThai.setText(TrangThai);
        txtMaSanPham.setText(MaSp);
        cbbTenSanPham.setSelectedItem(TenSp);
    }//GEN-LAST:event_tblIemiMouseClicked

    private void tblIemi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIemi1MouseClicked
        // TODO add your handling code here:
        int row = tblIemi1.getSelectedRow();
        if (row == -1) {
            return;
        }
        String IDImei = tblIemi1.getValueAt(row, 0).toString();
        String Imei = tblIemi1.getValueAt(row, 1).toString();
        String HDCT = tblIemi1.getValueAt(row, 2).toString();

        txtID_Imei1.setText(IDImei);
        txtImei1.setText(Imei);
        txtIDHDCT.setText(HDCT);
    }//GEN-LAST:event_tblIemi1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String keyword = txtSearch.getText();

        // Thực hiện tìm kiếm và cập nhật danh sách hiển thị
        ArrayList<Imei> results = repo.Search(page, limit, keyword);
        showImei(results);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        txtID_Imei1.setText("");
        txtImei1.setText("");
        txtIDHDCT.setText("");
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        txtID_Imei.setText("");
        txtImei.setText("");
        txtTrangThai.setText("");
        txtMaSanPham.setText("");
        cbbTenSanPham.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbbTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTenSanPhamActionPerformed
        // TODO add your handling code here:
        String ten = (String) cbbTenSanPham.getSelectedItem();
        dtm = (DefaultTableModel) this.tblIemi.getModel();
        dtm.setRowCount(0);
        for (Model.Imei imei : repo.SearchTen(page, limit, ten)) {
            Object[] row = {
                imei.getID_Imei(),
                imei.getMa_Imei(),
                imei.getTrang_thai() == 1 ? "Còn Hàng" : "Đã Bán",
                imei.getMa_San_Pham(),
                imei.getTen_San_Pham()
            };
            dtm.addRow(row);
        }
    }//GEN-LAST:event_cbbTenSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImeiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImeiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImeiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImeiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImeiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JComboBox<String> cbbTenSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPage;
    private javax.swing.JLabel lblPage1;
    private javax.swing.JTable tblIemi;
    private javax.swing.JTable tblIemi1;
    private javax.swing.JTextField txtIDHDCT;
    private javax.swing.JTextField txtID_Imei;
    private javax.swing.JTextField txtID_Imei1;
    private javax.swing.JTextField txtImei;
    private javax.swing.JTextField txtImei1;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
