/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View_Thuoc_Tinh;

import Repository.ImeiDaBanRepository;
import Repository.ImeiRepository;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nothank
 */
public class test extends javax.swing.JFrame {

    private ImeiRepository repo = new ImeiRepository();
    private ImeiDaBanRepository repoDB = new ImeiDaBanRepository();
    private DefaultTableModel dtm;
    private int page = 1;
    private int limit = 10;

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
                this.showImei(repo.getAll(page, limit));
    }

    private void showImei(ArrayList<Model.Imei> arr) {
        dtm = (DefaultTableModel) this.tblIemi.getModel();
        dtm.setRowCount(0);
        for (Model.Imei imei : arr) {
            Object[] row = {
                imei.getID_Imei(),
                imei.getMa_Imei(),
                imei.getTrang_thai() == 1 ? "Còn Hàng" : "Đã Bán",
                imei.getMa_San_Pham(),
                imei.getTen_San_Pham()
            };
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIemi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblIemi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Imei", "Imei", "Trạng Thái", "Mã Sản Phẩm", "Tên Sản Phẩm"
            }
        ));
        tblIemi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIemiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIemi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblIemiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIemiMouseClicked
        // TODO add your handling code here:
        int row = tblIemi.getSelectedRow();
        if (row == -1) {
            return;
        }
        String IDImei = tblIemi.getValueAt(row, 0).toString();
        String Imei = tblIemi.getValueAt(row, 1).toString();
        String TrangThai = tblIemi.getValueAt(row, 2).toString();
        String MaSp = tblIemi.getValueAt(row, 3).toString();
        String TenSp = tblIemi.getValueAt(row, 4).toString();

//        txtID_Imei.setText(IDImei);
//        txtImei.setText(Imei);
//        txtTrangThai.setText(TrangThai);
//        txtMaSanPham.setText(MaSp);
//        txtTenSanPham.setText(TenSp);
    }//GEN-LAST:event_tblIemiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIemi;
    // End of variables declaration//GEN-END:variables
}
