/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import Model.modelGiamGia;
import Repository.repoGiamGia;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nothank
 */
public class GiamGia extends javax.swing.JPanel {

    private Repository.repoGiamGia rp = new repoGiamGia();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;
    private Date ngayBatDau;
    private Date ngayKetThuc;

    /**
     * Creates new form NewJPanel
     */
    public GiamGia() {
        initComponents();

        this.fillTable(rp.getAll());
        this.fillTableS(rp.getAllS());
        this.fillTableD(rp.getAlld());

    }

    //Bảng tổng
    void fillTable(ArrayList<modelGiamGia> list) {
        mol = (DefaultTableModel) tblGG.getModel();
        mol.setRowCount(0);
        for (modelGiamGia x : list) {
            mol.addRow(x.toDataRow());
        }
    }

    //Bảng kết thúc
    void fillTableS(ArrayList<modelGiamGia> list) {
        mol = (DefaultTableModel) tblGGSap.getModel();
        mol.setRowCount(0);
        for (modelGiamGia x : list) {
            mol.addRow(x.toDataRow());
        }
    }

    //Bảng đâng diễn ra
    void fillTableD(ArrayList<modelGiamGia> list) {
        mol = (DefaultTableModel) tblGGDang.getModel();
        mol.setRowCount(0);
        for (modelGiamGia x : list) {
            mol.addRow(x.toDataRow());
        }
    }

//    
    // Phương thức xử lý khi người dùng chọn tab khác
//private void tabChanged() {
//    int selectedIndex = tabbedPane.getSelectedIndex();
//    if (selectedIndex == 0) {
//        this.fillTable(rp.getAll());  // Tab "Tất cả"
//    } else if (selectedIndex == 1) {
//        this.fillTableD(rp.getAlld());  // Tab "Đang diễn ra"
//    } else if (selectedIndex == 2) {
//        this.fillTableS(rp.getAllS());  // Tab "Sắp diễn ra"
//    }
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rdoSap = new javax.swing.JRadioButton();
        rdoDang = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtGiaTriDHToiThieu = new javax.swing.JTextField();
        txtMucGiamGia = new javax.swing.JTextField();
        txtMucGiamGiaToiDa = new javax.swing.JTextField();
        txtTenCT = new javax.swing.JTextField();
        txtmaGG = new javax.swing.JTextField();
        txtNgayKT = new com.toedter.calendar.JDateChooser();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGG = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnTK = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        rdoVND = new javax.swing.JRadioButton();
        rdoPhanTram = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGGSap = new javax.swing.JTable();
        txtGiaTriDHToiThieus = new javax.swing.JTextField();
        txtMucGiamGias = new javax.swing.JTextField();
        txtMucGiamGiaToiDas = new javax.swing.JTextField();
        txtTenCTs = new javax.swing.JTextField();
        txtmaGGS = new javax.swing.JTextField();
        txtNgayKTs = new com.toedter.calendar.JDateChooser();
        txtNgayBatDaus = new com.toedter.calendar.JDateChooser();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        rdoSaps = new javax.swing.JRadioButton();
        rdoDangs = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtMoTas = new javax.swing.JTextField();
        txtSoLuongs = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        rdoVNDs = new javax.swing.JRadioButton();
        rdoPhanTrams = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayBatDaud = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        rdoSapd = new javax.swing.JRadioButton();
        rdoDangd = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMoTad = new javax.swing.JTextField();
        txtSoLuongd = new javax.swing.JTextField();
        txtGiaTriDHToiThieud = new javax.swing.JTextField();
        txtMucGiamGiad = new javax.swing.JTextField();
        txtMucGiamGiaToiDad = new javax.swing.JTextField();
        txtTenCTd = new javax.swing.JTextField();
        txtmaGGd = new javax.swing.JTextField();
        txtNgayKTd = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGGDang = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        rdoVNDd = new javax.swing.JRadioButton();
        rdoPhanTramd = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(1074, 708));

        jPanel1.setPreferredSize(new java.awt.Dimension(1074, 708));

        jLabel3.setText("Mã giảm giá");

        jLabel4.setText("Tên chương trình");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jLabel5.setText("Mô tả");

        jLabel7.setText("Ngày bắt đầu");

        jLabel8.setText("Ngày kết thúc");

        buttonGroup2.add(rdoSap);
        rdoSap.setText("Kết thúc");
        rdoSap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSapActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoDang);
        rdoDang.setText("Đang diễn ra");
        rdoDang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoSap, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoDang)
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSap)
                    .addComponent(rdoDang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Kiểu giảm");

        jLabel10.setText("Số lượng");

        jLabel11.setText("Giá trị DH tối thiểu");

        jLabel12.setText("Mức giảm giá");

        jLabel13.setText("Mức giảm giá tối đa");

        jLabel14.setText("Trạng thái");

        txtmaGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaGGActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblGG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã giảm giá", "Tên chương trình", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Số lượng", "Kiểu giảm", "Giá trị DH tối thiểu", "Mức giảm giá", "Mức giảm giá tối đa", "Trạng thái"
            }
        ));
        tblGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGG);

        jButton1.setText("Tạo mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnTK.setText("Tìm kiếm");
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });
        btnTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnTKKeyReleased(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoVND);
        rdoVND.setText("VND");

        buttonGroup1.add(rdoPhanTram);
        rdoPhanTram.setSelected(true);
        rdoPhanTram.setText("Phần trăm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoPhanTram)
                .addGap(18, 18, 18)
                .addComponent(rdoVND)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoPhanTram)
                    .addComponent(rdoVND))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnTK)
                                .addGap(18, 18, 18)
                                .addComponent(btnLoad)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(83, 83, 83)
                                .addComponent(btnSua)
                                .addGap(68, 68, 68)
                                .addComponent(jButton1)
                                .addGap(226, 226, 226))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(44, 44, 44)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMucGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTenCT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtmaGG, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))
                                    .addGap(69, 71, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMoTa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtGiaTriDHToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtMucGiamGiaToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(870, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtmaGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtGiaTriDHToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtMucGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtMucGiamGiaToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(314, 314, 314)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Tất cả", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(1074, 708));

        tblGGSap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã giảm giá", "Tên chương trình", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Số lượng", "Kiểu giảm", "Giá trị DH tối thiểu", "Mức giảm giá", "Mức giảm giá tối đa", "Trạng thái"
            }
        ));
        tblGGSap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGGSapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGGSap);

        txtmaGGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaGGSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jLabel27.setText("Mã giảm giá");

        jLabel28.setText("Tên chương trình");

        jLabel29.setText("Mô tả");

        jLabel30.setText("Ngày bắt đầu");

        buttonGroup2.add(rdoSaps);
        rdoSaps.setText("Kết thúc");

        buttonGroup2.add(rdoDangs);
        rdoDangs.setText("Đang diễn ra");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoSaps, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoDangs, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSaps)
                    .addComponent(rdoDangs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel31.setText("Ngày kết thúc");

        jLabel32.setText("Kiểu giảm");

        jLabel33.setText("Số lượng");

        jLabel34.setText("Giá trị DH tối thiểu");

        jLabel35.setText("Mức giảm giá");

        jLabel36.setText("Mức giảm giá tối đa");

        jLabel37.setText("Trạng thái");

        buttonGroup1.add(rdoVNDs);
        rdoVNDs.setText("VND");

        buttonGroup1.add(rdoPhanTrams);
        rdoPhanTrams.setText("Phần trăm");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoPhanTrams)
                .addGap(18, 18, 18)
                .addComponent(rdoVNDs)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoPhanTrams)
                    .addComponent(rdoVNDs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addGap(50, 50, 50)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenCTs)
                                    .addComponent(txtmaGGS)
                                    .addComponent(txtMoTas)
                                    .addComponent(txtNgayBatDaus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgayKTs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoLuongs)
                                    .addComponent(txtGiaTriDHToiThieus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel36)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMucGiamGias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMucGiamGiaToiDas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(870, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtmaGGS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenCTs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(txtMoTas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(txtNgayBatDaus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(txtNgayKTs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel32))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSoLuongs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtGiaTriDHToiThieus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtMucGiamGias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtMucGiamGiaToiDas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel37)))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(311, 311, 311)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 256, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Kết thúc", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(1074, 708));

        jLabel6.setText("Mã giảm giá");

        jLabel15.setText("Tên chương trình");

        jLabel16.setText("Mô tả");

        jLabel17.setText("Ngày bắt đầu");

        jLabel18.setText("Ngày kết thúc");

        buttonGroup2.add(rdoSapd);
        rdoSapd.setText("Kết thúc");
        rdoSapd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSapdActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoDangd);
        rdoDangd.setText("Đang diễn ra");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(rdoSapd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoDangd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSapd)
                    .addComponent(rdoDangd))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel19.setText("Kiểu giảm");

        jLabel20.setText("Số lượng");

        jLabel21.setText("Giá trị DH tối thiểu");

        jLabel22.setText("Mức giảm giá");

        jLabel23.setText("Mức giảm giá tối đa");

        jLabel24.setText("Trạng thái");

        txtmaGGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaGGdActionPerformed(evt);
            }
        });

        tblGGDang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã giảm giá", "Tên chương trình", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Số lượng", "Kiểu giảm", "Giá trị DH tối thiểu", "Mức giảm giá", "Mức giảm giá tối đa", "Trạng thái"
            }
        ));
        tblGGDang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGGDangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGGDang);

        buttonGroup1.add(rdoVNDd);
        rdoVNDd.setText("VND");

        buttonGroup1.add(rdoPhanTramd);
        rdoPhanTramd.setText("Phần trăm");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoPhanTramd)
                .addGap(18, 18, 18)
                .addComponent(rdoVNDd)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoPhanTramd)
                    .addComponent(rdoVNDd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(jLabel22)
                        .addComponent(jLabel21)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMucGiamGiaToiDad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMucGiamGiad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGiaTriDHToiThieud, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMoTad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenCTd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgayBatDaud, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgayKTd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoLuongd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(txtmaGGd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmaGGd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenCTd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMoTad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayBatDaud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayKTd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuongd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(14, 14, 14))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtGiaTriDHToiThieud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtMucGiamGiad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtMucGiamGiaToiDad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đang diễn ra", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaGGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaGGActionPerformed

    private void txtmaGGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaGGdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaGGdActionPerformed

    private void rdoDangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDangActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
//        if (this.readForm() != null) {
//                String ma = tbl_bang.getValueAt(i, 0).toString();
//                if (rp.checkTrung(ma) != null) {
//                    JOptionPane.showMessageDialog(this, "trung ma");
//                } else {
//                    rp.them(this.readForm());
//                    JOptionPane.showMessageDialog(this, "them ok");
//                    this.fillTable(rp.getAll());
//                }
        //Thêm
//        
// Kiểm tra ID nhân viên
//        if (validateIDNhanVien()) {
//            // Kiểm tra các điều kiện khác
//            if (check()) {
//                // Kiểm tra trùng lặp
//                if (checkTrung()) {
//                    // Lấy giá trị ngày kết thúc từ JDateChooser
//                    Date utilNgayKetThuc = jDateChooserEndDate.getDate(); // Lấy giá trị từ JDateChooser
//
//                    // Kiểm tra ngày kết thúc
//                    if (isEndDateValid(utilNgayKetThuc)) {
//                        // Thực hiện thêm mới nếu tất cả điều kiện đã được thoả mãn
//                        if (rp.them(this.readform()) > 0) {
//                            // Thêm thành công
//                            JOptionPane.showMessageDialog(this, "Thêm thành công");
//                            this.fillTable(rp.getAll());
//                            this.fillTableS(rp.getAllS());
//                            this.fillTableD(rp.getAlld());
//                        } else {
//                            JOptionPane.showMessageDialog(this, "Thêm thất bại");
//                        }
//                    } // Nếu isEndDateValid trả về false, không làm gì cả
//                }
//            }
//        }

//         if (check()) {
//                if (checkTrung()) {
//                    if (rp.them(this.readform()) > 0) {
//                        //thêm được
//                        JOptionPane.showMessageDialog(this, "them thanh cong");
//                        this.fillTable(rp.getAll());
//                        this.fillTableS(rp.getAllS());
//                        this.fillTableD(rp.getAlld());
//                    } else {
//                        JOptionPane.showMessageDialog(this, "them that bai");
//                    }
//                }
//            }
        if (check()) {
    // Lấy ngày bắt đầu và ngày kết thúc từ JDateChooser
    
    // Kiểm tra khoảng thời gian ngày
    if (isDateRangeValid(ngayBatDau, ngayKetThuc)) {
        if (checkTrung()) {
            if (rp.them(this.readform()) > 0) {
                // Thêm được
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                this.fillTable(rp.getAll());
                this.fillTableS(rp.getAllS());
                this.fillTableD(rp.getAlld());
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
    }
}


    }//GEN-LAST:event_btnThemActionPerformed

    private boolean isDateRangeValid(java.sql.Date startDate, java.sql.Date endDate) {
    java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis()); // Lấy ngày hiện tại

    // Kiểm tra ngày bắt đầu
    if (!startDate.before(currentDate)) {
        JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải trước ngày hiện tại!");
        return false; // Ngày bắt đầu không hợp lệ
    }

    // Kiểm tra ngày kết thúc
    if (endDate.before(currentDate)) {
        JOptionPane.showMessageDialog(this, "Ngày kết thúc không được trước ngày hiện tại!");
        return false; // Ngày kết thúc không hợp lệ
    }

    return true; // Cả ngày bắt đầu và ngày kết thúc đều hợp lệ
}

//    private boolean isEndDateValid(Date utilNgayKetThuc) {
//        // Chuyển đổi ngày kết thúc từ kiểu java.util.Date sang java.sql.Date
//        java.sql.Date ngayKetThuc = utilNgayKetThuc != null ? new java.sql.Date(utilNgayKetThuc.getTime()) : null;
//
//        if (ngayKetThuc == null) {
//            // Nếu ngày kết thúc không được chọn
//            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày kết thúc.");
//            return false; // Ngày kết thúc không hợp lệ
//        }
//
//        // Lấy ngày hiện tại của hệ thống
//        LocalDate currentDate = LocalDate.now();
//        LocalDate endDate = ngayKetThuc.toLocalDate();
//
//        // Kiểm tra nếu ngày kết thúc phải là sau ngày hiện tại
//        if (!endDate.isAfter(currentDate)) {
//            JOptionPane.showMessageDialog(null, "Ngày kết thúc phải sau ngày hiện tại.");
//            return false; // Ngày kết thúc không hợp lệ
//        }
//
//        return true; // Ngày kết thúc hợp lệ
//    }
//bảng tổng
    private void tblGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGGMouseClicked
        // TODO add your handling code here:
        i = tblGG.getSelectedRow();

// Không còn txtIDNhanVien nữa
txtmaGG.setText(tblGG.getValueAt(i, 0).toString());
txtTenCT.setText(tblGG.getValueAt(i, 1).toString());
txtMoTa.setText(tblGG.getValueAt(i, 2).toString());
txtNgayBatDau.setDate((Date) tblGG.getValueAt(i, 3));
txtNgayKT.setDate((Date) tblGG.getValueAt(i, 4));
txtSoLuong.setText(tblGG.getValueAt(i, 5).toString());

if (tblGG.getValueAt(i, 6).toString().equalsIgnoreCase("VND")) {
    rdoVND.setSelected(true);
} else {
    rdoPhanTram.setSelected(true);
}

txtGiaTriDHToiThieu.setText(tblGG.getValueAt(i, 7).toString());
txtMucGiamGia.setText(tblGG.getValueAt(i, 8).toString());
txtMucGiamGiaToiDa.setText(tblGG.getValueAt(i, 9).toString());

if (tblGG.getValueAt(i, 10).toString().equalsIgnoreCase("Đang diễn ra")) {
    rdoDang.setSelected(true);
} else {
    rdoSap.setSelected(true);
}

// Không cần thiết phải vô hiệu hóa txtIDNhanVien
txtmaGG.setEnabled(false);

    }//GEN-LAST:event_tblGGMouseClicked
//check ngày bắt đầu không được sau ngày kết thúc

    private boolean check() {
        java.util.Date utilNgayBatDau = txtNgayBatDau.getDate(); // Giả sử txtNgayBatDau là JDateChooser
        ngayBatDau = new java.sql.Date(utilNgayBatDau.getTime());
        java.util.Date utilNgayKetThuc = txtNgayKT.getDate();
        ngayKetThuc = new java.sql.Date(utilNgayKetThuc.getTime());
        if (ngayBatDau == null || ngayKetThuc == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn đầy đủ ngày bắt đầu và ngày kết thúc!");
            return false;
        } else if (ngayKetThuc.before(ngayBatDau)) {
            JOptionPane.showMessageDialog(null, "Ngày kết thúc phải sau ngày bắt đầu!");
            return false;
        } else {
            return true;
        }
    }

    //Check trùng mã
    private boolean checkTrung() {

        if (rp.checkTrungMa(txtmaGG.getText())) {
            JOptionPane.showMessageDialog(this, "Mã phiếu đã tồn tại !!!");
            return false;
        } else {
            return true;
        }
    }

 


    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemMouseClicked
    //sửa
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        i = tblGG.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng");
        } else {
            if (check()) {
                String maGiamGiaTruoc = tblGG.getValueAt(i, 0).toString(); // Lấy mã giảm giá từ bảng trước khi cập nhật
                String maGiamGiaMoi = txtmaGG.getText().trim(); // Lấy mã giảm giá từ trường nhập liệu

                // Kiểm tra nếu mã giảm giá mới khác với mã giảm giá cũ
                if (!maGiamGiaTruoc.equals(maGiamGiaMoi)) {
                    JOptionPane.showMessageDialog(this, "Không thể thay đổi mã giảm giá");
                    return; // Dừng quá trình cập nhật
                }

                if (rp.sua(maGiamGiaMoi, this.readform()) > 0) {
                    JOptionPane.showMessageDialog(this, "cập nhật thanh cong");
                    this.fillTable(rp.getAll());
                    this.fillTableS(rp.getAllS());
                    this.fillTableD(rp.getAlld());
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }

        }
    }//GEN-LAST:event_btnSuaActionPerformed

    //bảng đang diễn ra
    private void tblGGDangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGGDangMouseClicked
        // TODO add your handling code here:
       // TODO add your handling code here:
i = tblGGDang.getSelectedRow();

// Không còn txtIDNhanViend nữa
// txtIDNhanViend.setText(tblGGDang.getValueAt(i, 0).toString()); // Xóa dòng này

txtmaGGd.setText(tblGGDang.getValueAt(i, 0).toString());
txtTenCTd.setText(tblGGDang.getValueAt(i, 1).toString());
txtMoTad.setText(tblGGDang.getValueAt(i, 2).toString());
txtNgayBatDaud.setDate((Date) tblGGDang.getValueAt(i, 3));
txtNgayKTd.setDate((Date) tblGGDang.getValueAt(i, 4));
txtSoLuongd.setText(tblGGDang.getValueAt(i, 5).toString());

if (tblGGDang.getValueAt(i, 6).toString().equalsIgnoreCase("VND")) {
    rdoVNDd.setSelected(true);
} else {
    rdoPhanTramd.setSelected(true);
}

txtGiaTriDHToiThieud.setText(tblGGDang.getValueAt(i, 7).toString());
txtMucGiamGiad.setText(tblGGDang.getValueAt(i, 8).toString());
txtMucGiamGiaToiDad.setText(tblGGDang.getValueAt(i, 9).toString());

if (tblGGDang.getValueAt(i, 10).toString().equalsIgnoreCase("Đang diễn ra")) {
    rdoDangd.setSelected(true);
} else {
    rdoSapd.setSelected(true);
}


    }//GEN-LAST:event_tblGGDangMouseClicked

    private void rdoSapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoSapActionPerformed

    private void txtmaGGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaGGSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaGGSActionPerformed
    //bang
    private void tblGGSapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGGSapMouseClicked
        // TODO add your handling code here:
        i = tblGGSap.getSelectedRow();

// Không còn txtIDNhanVienS nữa
// txtIDNhanVienS.setText(tblGGSap.getValueAt(i, 0).toString()); // Xóa dòng này

txtmaGGS.setText(tblGGSap.getValueAt(i, 0).toString());
txtTenCTs.setText(tblGGSap.getValueAt(i, 1).toString());
txtMoTas.setText(tblGGSap.getValueAt(i, 2).toString());

txtNgayBatDaus.setDate((Date) tblGGSap.getValueAt(i, 3));
txtNgayKTs.setDate((Date) tblGGSap.getValueAt(i, 4));
txtSoLuongs.setText(tblGGSap.getValueAt(i, 5).toString());

if (tblGGSap.getValueAt(i, 6).toString().equalsIgnoreCase("VND")) {
    rdoVNDs.setSelected(true);
} else {
    rdoPhanTrams.setSelected(true);
}

txtGiaTriDHToiThieus.setText(tblGGSap.getValueAt(i, 7).toString());
txtMucGiamGias.setText(tblGGSap.getValueAt(i, 8).toString());
txtMucGiamGiaToiDas.setText(tblGGSap.getValueAt(i, 9).toString());

if (tblGGSap.getValueAt(i, 10).toString().equalsIgnoreCase("Đang diễn ra")) {
    rdoDangs.setSelected(true);
} else {
    rdoSaps.setSelected(true);
}


    }//GEN-LAST:event_tblGGSapMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        txtmaGG.setEnabled(true);
        txtmaGG.setText("");
        txtTenCT.setText("");
        txtMoTa.setText("");
        txtNgayBatDau.setDate(null);
        txtNgayKT.setDate(null);
        txtSoLuong.setText("");
        txtGiaTriDHToiThieu.setText("");

        txtMucGiamGia.setText("");
        txtMucGiamGiaToiDa.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnTKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTKKeyReleased

    }//GEN-LAST:event_btnTKKeyReleased

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        // TODO add your handling code here:
        // Lấy giá trị từ trường tìm kiếm
        String keyword = txtSearch.getText().trim(); // lấy văn bản hiện tại từ txtSearch và loại bỏ khoảng trắng thừa

        // Kiểm tra nếu trường tìm kiếm rỗng
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã giảm giá để tìm kiếm!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return; // Dừng lại nếu người dùng không nhập gì
        }

        // Thực hiện tìm kiếm giảm giá
        ArrayList<modelGiamGia> results = this.rp.searchGiamGia(keyword); // repoGG là đối tượng repository của bạn

        // Cập nhật giao diện người dùng với kết quả tìm kiếm
        DefaultTableModel dtm = (DefaultTableModel) tblGG.getModel();
        dtm.setRowCount(0); // xóa tất cả hàng trong bảng

        // Kiểm tra nếu không có kết quả trả về
        if (results == null || results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã giảm giá nào phù hợp!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            return; // không làm gì nếu không có kết quả
        } else {
            JOptionPane.showMessageDialog(this, "Tìm kiếm thành công! Đã tìm thấy mã giảm giá phù hợp.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

        // Thêm các hàng mới vào bảng với kết quả tìm kiếm
        for (modelGiamGia gg : results) {
            Object[] row = {
                gg.getIDNhanVien(),
                gg.getMaGiamGia(),
                gg.getTenChuongTrinh(),
                gg.getMoTa(),
                gg.getNgayBatDau(),
                gg.getNgayKetThuc(),
                gg.getSoLuong(),
                gg.getKieuGiam(),
                gg.getGiaTriDHToiThieu(),
                gg.getMucGiamGia(),
                gg.getMucGiamGiaToiDa(),
                gg.getTrangThai()
            };
            dtm.addRow(row); // Thêm hàng vào bảng
        }
    }//GEN-LAST:event_btnTKActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        this.fillTable(rp.getAll());

    }//GEN-LAST:event_btnLoadActionPerformed

    private void rdoSapdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSapdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoSapdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTK;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdoDang;
    private javax.swing.JRadioButton rdoDangd;
    private javax.swing.JRadioButton rdoDangs;
    private javax.swing.JRadioButton rdoPhanTram;
    private javax.swing.JRadioButton rdoPhanTramd;
    private javax.swing.JRadioButton rdoPhanTrams;
    private javax.swing.JRadioButton rdoSap;
    private javax.swing.JRadioButton rdoSapd;
    private javax.swing.JRadioButton rdoSaps;
    private javax.swing.JRadioButton rdoVND;
    private javax.swing.JRadioButton rdoVNDd;
    private javax.swing.JRadioButton rdoVNDs;
    private javax.swing.JTable tblGG;
    private javax.swing.JTable tblGGDang;
    private javax.swing.JTable tblGGSap;
    private javax.swing.JTextField txtGiaTriDHToiThieu;
    private javax.swing.JTextField txtGiaTriDHToiThieud;
    private javax.swing.JTextField txtGiaTriDHToiThieus;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtMoTad;
    private javax.swing.JTextField txtMoTas;
    private javax.swing.JTextField txtMucGiamGia;
    private javax.swing.JTextField txtMucGiamGiaToiDa;
    private javax.swing.JTextField txtMucGiamGiaToiDad;
    private javax.swing.JTextField txtMucGiamGiaToiDas;
    private javax.swing.JTextField txtMucGiamGiad;
    private javax.swing.JTextField txtMucGiamGias;
    private com.toedter.calendar.JDateChooser txtNgayBatDau;
    private com.toedter.calendar.JDateChooser txtNgayBatDaud;
    private com.toedter.calendar.JDateChooser txtNgayBatDaus;
    private com.toedter.calendar.JDateChooser txtNgayKT;
    private com.toedter.calendar.JDateChooser txtNgayKTd;
    private com.toedter.calendar.JDateChooser txtNgayKTs;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuongd;
    private javax.swing.JTextField txtSoLuongs;
    private javax.swing.JTextField txtTenCT;
    private javax.swing.JTextField txtTenCTd;
    private javax.swing.JTextField txtTenCTs;
    private javax.swing.JTextField txtmaGG;
    private javax.swing.JTextField txtmaGGS;
    private javax.swing.JTextField txtmaGGd;
    // End of variables declaration//GEN-END:variables
modelGiamGia readform() {
        
        String maGiamGia;
        String tenChuongTrinh;
        String moTa;

        java.sql.Date ngayBatDau = null;
        java.sql.Date ngayKetThuc;
        int soLuong;
        int kieuGiam;
        float giaTriDHToiThieu;
        int mucGiamGia;
        int mucGiamGiaToiDa;
        int trangThai;
//        check ID nhân viên
        

        //checl mã
        maGiamGia = txtmaGG.getText().trim();
        if (maGiamGia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ban chua nhap ma");
            txtmaGG.requestFocus();
            return null;
        }
        //check tên
        tenChuongTrinh = txtTenCT.getText().trim();
        if (tenChuongTrinh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ban chua nhap tên chương trình");
            txtTenCT.requestFocus();
            return null;
        }
        //check mô tả
        moTa = txtMoTa.getText().trim();
        if (moTa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mô tả");
            txtMoTa.requestFocus();
            return null;
        }
        //check mô tả
        moTa = txtMoTa.getText().trim();
        if (moTa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mô tả");
            txtMoTa.requestFocus();
            return null;
        }
        //check ngày bắt đầu
        java.util.Date utilNgayBatDau = txtNgayBatDau.getDate();
        if (utilNgayBatDau != null) {
            ngayBatDau = new java.sql.Date(utilNgayBatDau.getTime());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = sdf.format(ngayBatDau);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày bắt đầu!");
        }
        //check ngày kết thúc
        java.util.Date utilNgayKetThuc = txtNgayKT.getDate();
        ngayKetThuc = new java.sql.Date(utilNgayKetThuc.getTime());
        if (utilNgayKetThuc != null) {

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = sdf.format(ngayKetThuc);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày bắt đầu!");
        }
        //check số lượng
        String inputSL = txtSoLuong.getText().trim();  // Lấy giá trị và loại bỏ khoảng trắng
        if (inputSL.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng!");  // Thông báo nếu để trống
            txtSoLuong.requestFocus();
            return null;
        }
        soLuong = Integer.parseInt(txtSoLuong.getText().trim());
        if (soLuong <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng sai định dạng");
            txtSoLuong.requestFocus();
            return null;
        }
        // check giá trị
        String inputGTDH = txtGiaTriDHToiThieu.getText().trim();  // Lấy giá trị và loại bỏ khoảng trắng
        if (inputGTDH.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập giá trị đơn hàng!");  // Thông báo nếu để trống
            txtGiaTriDHToiThieu.requestFocus();
            return null;
        }
        giaTriDHToiThieu = Float.parseFloat(txtGiaTriDHToiThieu.getText().trim());
        if (giaTriDHToiThieu <= 0) {
            JOptionPane.showMessageDialog(this, "Giá trị đơn hàng sai định dạng");
            txtGiaTriDHToiThieu.requestFocus();
            return null;
        }

        //check mức giảm giá
        String inputMGG = txtMucGiamGia.getText().trim();  // Lấy giá trị và loại bỏ khoảng trắng
        if (inputMGG.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mức giá!");  // Thông báo nếu để trống
            txtMucGiamGia.requestFocus();
            return null;
        }
        if (rdoPhanTram.isSelected()) {
            mucGiamGia = Integer.parseInt(txtMucGiamGia.getText().trim());
            if (mucGiamGia < 1 || mucGiamGia > 100) {
                JOptionPane.showMessageDialog(this, "Mức giảm giá sai định dạng");
                txtMucGiamGia.requestFocus();
                return null;
            }
        }

        //check mức giảm giá tối đa
        String inputMGGTD = txtMucGiamGiaToiDa.getText().trim();  // Lấy giá trị và loại bỏ khoảng trắng
        if (inputMGGTD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mức giảm giá tối đa!");  // Thông báo nếu để trống
            txtMucGiamGiaToiDa.requestFocus();
            return null;
        }

        mucGiamGiaToiDa = Integer.parseInt(txtMucGiamGiaToiDa.getText().trim());
        if (mucGiamGiaToiDa <= 0) {
            JOptionPane.showMessageDialog(this, "Mức giảm giá tối đa sai định dạng");
            txtMucGiamGiaToiDa.requestFocus();
            return null;
        }
        //check validate giá
        mucGiamGia = Integer.parseInt(txtMucGiamGia.getText().trim());
        if (giaTriDHToiThieu <= mucGiamGia || giaTriDHToiThieu <= mucGiamGiaToiDa) {
            JOptionPane.showMessageDialog(this, "Giá trị đơn hàng không được nhỏ hơn mức giảm giá");
            txtMucGiamGia.requestFocus();
            txtMucGiamGiaToiDa.requestFocus();
            return null;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);  // Không cho phép định dạng ngày không hợp lệ
        //check trạng thái
        if (rdoDang.isSelected()) {
            trangThai = 1;
        } else {
            trangThai = 0;
        }

        if (rdoPhanTram.isSelected()) {
            kieuGiam = 1;
        } else {
            kieuGiam = 0;
            mucGiamGia = 0;
            JOptionPane.showMessageDialog(this, "Mã giảm giá là VND nên mức giảm giá sẽ không được áp dụng và được tự động chuyển về 0");
//            txtMucGiamGia.setEnabled(false);
            txtMucGiamGia.setText("0");

        }

// Lấy giá trị từ các JDateChooser
// Kiểm tra các giá trị ngày có hợp lệ (không trống)
        // Kiểm tra ngày kết thúc có sau ngày bắt đầu không
        if (ngayBatDau == null || ngayKetThuc == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn đầy đủ ngày bắt đầu và ngày kết thúc!");
        } else {
            // Kiểm tra ngày kết thúc có sau ngày bắt đầu không
            if (ngayBatDau.before(ngayKetThuc)) {
                // Ngày kết thúc hợp lệ, tiếp tục xử lý
                JOptionPane.showMessageDialog(null, "Ngày kết thúc hợp lệ!");
            } else {
                // Ngày kết thúc không hợp lệ
                JOptionPane.showMessageDialog(null, "Ngày kết thúc phải sau ngày bắt đầu!");
            }
        }

        // Giả sử jDateChooserNgayBatDau và jDateChooserNgayKetThuc là các đối tượng JDateChooser cho ngày bắt đầu và ngày kết thúc
// Chuyển đổi ngày bắt đầu và ngày kết thúc từ kiểu java.util.Date sang java.sql.Date
        ngayBatDau = utilNgayBatDau != null ? new java.sql.Date(utilNgayBatDau.getTime()) : null;
        ngayKetThuc = utilNgayKetThuc != null ? new java.sql.Date(utilNgayKetThuc.getTime()) : null;

        if (ngayBatDau != null && ngayKetThuc != null) {
            // Lấy ngày hiện tại của hệ thống
            LocalDate currentDate = LocalDate.now();
            LocalDate startDate = ngayBatDau.toLocalDate();
            LocalDate endDate = ngayKetThuc.toLocalDate();

            // Kiểm tra nếu ngày bắt đầu phải trước ngày hiện tại
            if (startDate.isAfter(currentDate)) {
                JOptionPane.showMessageDialog(null, "Ngày bắt đầu phải trước ngày hiện tại.");
                return null; // Dừng thực hiện các lệnh tiếp theo và thoát khỏi phương thức nếu ngày bắt đầu không hợp lệ
            }

            // Kiểm tra nếu ngày kết thúc đã qua ngày hiện tại và trạng thái là "Đang diễn ra"
            if (endDate.isBefore(currentDate) && trangThai == 1) { // 1 là trạng thái "Đang diễn ra"
                trangThai = 0; // Chuyển trạng thái thành "Kết thúc"
                rdoSap.setSelected(true); // Đánh dấu radio button "Kết thúc" được chọn
                JOptionPane.showMessageDialog(null, "Chương trình đã chuyển trạng thái thành 'Kết thúc' do ngày kết thúc đã qua.");
                // Dừng thực hiện các lệnh tiếp theo và thoát khỏi phương thức
            } else {
                trangThai = 1; // Giữ nguyên trạng thái "Đang diễn ra"
                rdoDang.setSelected(true); // Đánh dấu radio button "Đang diễn ra" được chọn
                JOptionPane.showMessageDialog(this, "Mã giảm giá vẫn đang diễn ra.");
            }
        }

        return new modelGiamGia( maGiamGia, tenChuongTrinh, moTa, ngayBatDau, ngayKetThuc, soLuong, kieuGiam, giaTriDHToiThieu, mucGiamGia, mucGiamGiaToiDa, trangThai);
    }

}
