/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import Repository.NhanVienRepository;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.NhanVienModel;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import Repository.NhanVienRepository;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nothank
 */
public class NhanVien extends javax.swing.JPanel {

    private NhanVienRepository rp = new NhanVienRepository();
    private DefaultTableModel mol = new DefaultTableModel();
    ArrayList<NhanVienModel> list = new ArrayList<>();
    private int i = -1;
    private String path = "D/...";
    NhanVienRepository showData = new NhanVienRepository();

    /**
     * Creates new form NewJPanel
     */
    public NhanVien() {
        initComponents();
        fillTable(rp.getAll());
        init();
        fillTable1(rp.getAll1());

        cbo_chucVu.removeAllItems();
        cbo_chucVu1.removeAllItems();
        cbo_gioiTinh.removeAllItems();
        cbo_CV.removeAllItems();
        txt_maNV.setEnabled(false);
        cbo_chucVu.addItem("Quản Lý");
        cbo_chucVu.addItem("Nhân Viên");

        cbo_trangThai.removeAllItems();
        cbo_chucVu1.addItem("Quản Lý");
        cbo_chucVu1.addItem("Nhân Viên");

        cbo_gioiTinh.addItem("Tất Cả");
        cbo_gioiTinh.addItem("Nam");
        cbo_gioiTinh.addItem("Nữ");

        cbo_CV.addItem("Tất Cả");
        cbo_CV.addItem("Quản Lý");
        cbo_CV.addItem("Nhân Viên");

    }

    public void init() {
        lbhinhAnh.setText("");
    }

    void fillTable(ArrayList<NhanVienModel> list) {
        mol = (DefaultTableModel) tbl_bangNhanVien.getModel();
        mol.setRowCount(0);
        for (NhanVienModel nhanVienModel : list) {
            mol.addRow(new Object[]{
                nhanVienModel.getMaNV(), nhanVienModel.getTaiKhoan(),
                nhanVienModel.getMatKhau(), nhanVienModel.getHoTen(), nhanVienModel.isGioiTinh() ? "Nam" : "Nữ",
                nhanVienModel.getNgaySinh(), nhanVienModel.getDiaChi(), nhanVienModel.getSDT(),
                nhanVienModel.getEmail(), nhanVienModel.getTrangThai() == 0 ? "Đang Làm" : "Nghỉ Làm",
                nhanVienModel.getChucVu(), nhanVienModel.getNgayBatDau()
            });

        }
    }

    void fillTable1(ArrayList<NhanVienModel> list) {
        mol = (DefaultTableModel) tbl_bangNhanVien1.getModel();
        mol.setRowCount(0);
        for (NhanVienModel nhanVienModel : list) {
            mol.addRow(new Object[]{
                nhanVienModel.getMaNV(), nhanVienModel.getTaiKhoan(),
                nhanVienModel.getMatKhau(), nhanVienModel.getHoTen(), nhanVienModel.isGioiTinh() ? "Nam" : "Nữ",
                nhanVienModel.getNgaySinh(), nhanVienModel.getDiaChi(), nhanVienModel.getSDT(),
                nhanVienModel.getEmail(), nhanVienModel.getTrangThai() == 0 ? "Đang Làm" : "Nghỉ Làm",
                nhanVienModel.getChucVu(), nhanVienModel.getNgayBatDau()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField9 = new javax.swing.JTextField();
        cbo_trangThai = new javax.swing.JComboBox<>();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TimKiem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bangNhanVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ngaySinh = new com.toedter.calendar.JDateChooser();
        txt_sdt = new javax.swing.JTextField();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_taiKhoan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_matKhau = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbo_chucVu = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_ngayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        lbhinhAnh = new javax.swing.JLabel();
        rdo_dangLam = new javax.swing.JRadioButton();
        rdo_nghiLam = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbo_gioiTinh = new javax.swing.JComboBox<>();
        cbo_CV = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bangNhanVien1 = new javax.swing.JTable();
        lbhinhAnh1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_hoTen1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_email1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_sdt1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rdo_nam1 = new javax.swing.JRadioButton();
        rdo_nu1 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        txt_ngaySinh1 = new com.toedter.calendar.JDateChooser();
        txt_ngayBatDau1 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        rdo_dangLam1 = new javax.swing.JRadioButton();
        rdo_nghiLam1 = new javax.swing.JRadioButton();
        cbo_chucVu1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_diaChi1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_matKhau1 = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        txt_taiKhoan1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_maNV1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btn_sua2 = new javax.swing.JButton();

        jToggleButton3.setText("jToggleButton3");

        jToggleButton4.setText("jToggleButton4");

        jLabel1.setText("Nhan Vien");

        jToggleButton2.setText("jToggleButton2");

        jToggleButton1.setText("jToggleButton1");

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField2.setText("jTextField2");

        setPreferredSize(new java.awt.Dimension(719, 521));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });
        TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TimKiemKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Tìm Kiếm:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 352, Short.MAX_VALUE))
                    .addComponent(TimKiem))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_bangNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Vien", "Tài Khoản", "Mật Khẩu", "Họ Tên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "SĐT", "Email", "Trạng Thái", "Chức Vụ", "Ngày Bắt Đầu"
            }
        ));
        tbl_bangNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bangNhanVien);

        jLabel2.setText("Email");

        jLabel3.setText("Họ Và Tên");

        jLabel4.setText("Số Điện Thoại");

        jLabel5.setText("Giới Tính");

        jLabel6.setText("Ngày Sinh");

        buttonGroup1.add(rdo_nam);
        rdo_nam.setSelected(true);
        rdo_nam.setText("Nam");

        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("Nữ");

        jLabel7.setText("Mã NV");

        jLabel8.setText("Tài Khoản");

        txt_taiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_taiKhoanActionPerformed(evt);
            }
        });

        jLabel9.setText("Mật Khẩu");

        jLabel10.setText("Địa Chỉ");

        jLabel11.setText("Chức Vụ");

        cbo_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Ngày Bắt Đầu");

        jLabel13.setText("Trạng Thái");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_lamMoi.setText("Làm Mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        lbhinhAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbhinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbhinhAnhMouseClicked(evt);
            }
        });

        buttonGroup2.add(rdo_dangLam);
        rdo_dangLam.setSelected(true);
        rdo_dangLam.setText("Đang Làm");

        buttonGroup2.add(rdo_nghiLam);
        rdo_nghiLam.setText("Nghỉ Làm");

        jButton2.setText("Xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbo_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_gioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_gioiTinhActionPerformed(evt);
            }
        });

        cbo_CV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_CV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_CVActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Lọc");

        jLabel28.setText("Giới Tính");

        jLabel29.setText("Chức Vụ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_gioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_CV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_CV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rdo_nam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_sdt)
                            .addComponent(txt_email)
                            .addComponent(txt_hoTen)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbhinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdo_dangLam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(rdo_nghiLam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbo_chucVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_diaChi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_matKhau, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_maNV, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_taiKhoan, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txt_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbhinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_hoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txt_matKhau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(txt_diaChi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_chucVu))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdo_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdo_dangLam)
                                    .addComponent(rdo_nghiLam))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ngayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_them, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_lamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("Danh Sách Nhân Viên Đang Làm Việc", jPanel2);

        tbl_bangNhanVien1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Vien", "Tài Khoản", "Mật Khẩu", "Họ Ten", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "SĐT", "Email", "Trạng Thái", "Chức Vụ", "Ngày Bắt Đầu"
            }
        ));
        tbl_bangNhanVien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangNhanVien1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_bangNhanVien1);

        lbhinhAnh1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbhinhAnh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbhinhAnh1MouseClicked(evt);
            }
        });

        jLabel15.setText("Họ Và Tên");

        jLabel16.setText("Email");

        jLabel17.setText("Số Điện Thoại");

        jLabel18.setText("Giới Tính");

        buttonGroup1.add(rdo_nam1);
        rdo_nam1.setText("Nam");

        buttonGroup1.add(rdo_nu1);
        rdo_nu1.setText("Nữ");

        jLabel19.setText("Ngày Sinh");

        jLabel20.setText("Ngày Bắt Đầu");

        buttonGroup2.add(rdo_dangLam1);
        rdo_dangLam1.setText("Đang Làm");

        buttonGroup2.add(rdo_nghiLam1);
        rdo_nghiLam1.setText("Nghỉ Làm");

        cbo_chucVu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("Trạng Thái");

        jLabel22.setText("Chức Vụ");

        jLabel23.setText("Địa Chỉ");

        jLabel24.setText("Mật Khẩu");

        txt_taiKhoan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_taiKhoan1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Tài Khoản");

        jLabel26.setText("Mã NV");

        btn_sua2.setText("Khôi Phục");
        btn_sua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sua2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaySinh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sdt1)
                            .addComponent(txt_email1)
                            .addComponent(txt_hoTen1)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbhinhAnh1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_maNV1)
                                    .addComponent(txt_taiKhoan1)
                                    .addComponent(txt_matKhau1)
                                    .addComponent(txt_diaChi1)
                                    .addComponent(cbo_chucVu1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_ngayBatDau1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rdo_nam1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_nu1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_dangLam1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_nghiLam1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sua2)
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_maNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_taiKhoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbhinhAnh1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_hoTen1)
                    .addComponent(txt_matKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_email1)
                    .addComponent(txt_diaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_sdt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_chucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo_dangLam1)
                            .addComponent(rdo_nghiLam1)
                            .addComponent(rdo_nu1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdo_nam1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ngaySinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngayBatDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_sua2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(83, 83, 83))
        );

        jTabbedPane1.addTab("Danh Sách Nhân Viên Đã Nghỉ Việc", jPanel1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_taiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_taiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_taiKhoanActionPerformed

    private void tbl_bangNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangNhanVienMouseClicked
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_tbl_bangNhanVienMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        NhanVienModel nv = readForm();
        if (nv == null) {
            return;
        }
        nv.setMaNV(rp.generateMaNV());
        listNhanVien = rp.getAll();
        if (checkTrung(nv)) {
            return; 
        } else {
            if (rp.Them(nv) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                this.fillTable(rp.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
        this.fillTable1(rp.getAll1());
    }//GEN-LAST:event_btn_themActionPerformed

    private void lbhinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbhinhAnhMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int kq = chooser.showOpenDialog(null);
        if (kq == JFileChooser.APPROVE_OPTION) {
            path = chooser.getSelectedFile().getPath();
            ImageIcon icon = new ImageIcon(path);
            lbhinhAnh.setIcon(icon);
        }
    }//GEN-LAST:event_lbhinhAnhMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int i = tbl_bangNhanVien.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng nào để sửa!");
            return;
        }
        String ma = tbl_bangNhanVien.getValueAt(i, 0).toString();
        NhanVienModel nv = readForm();
        if (nv == null) {
            return;
        }
        if (checkTrungKhiSua(nv, ma)) {
            return;
        }
        if (rp.Sua(ma, nv) > 0) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            this.fillTable(rp.getAll()); // Cập nhật bảng sau khi sửa thành công
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        fillTable1(rp.getAll1());
    }//GEN-LAST:event_btn_suaActionPerformed

    private void tbl_bangNhanVien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangNhanVien1MouseClicked
        // TODO add your handling code here:
        showData1();
    }//GEN-LAST:event_tbl_bangNhanVien1MouseClicked

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
        txt_maNV.setText("");
        txt_taiKhoan.setText("");
        txt_matKhau.setText("");
        txt_diaChi.setText("");
        txt_hoTen.setText("");
        txt_email.setText("");
        txt_sdt.setText("");
        txt_ngaySinh.setDate(null);
        txt_ngayBatDau.setDate(null);
        lbhinhAnh.setIcon(null);
        lbhinhAnh.setText("           Thêm ảnh mới");

    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook wordbook = new XSSFWorkbook();
            XSSFSheet sheet = wordbook.createSheet("Thông Tin Cá Nhân");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(3);

            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Nhân Viên");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Tài Khoản");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Mật Khẩu");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Họ Tên");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Giới Tính");

            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Ngày Sinh");

            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Địa Chỉ");

            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue("Số Điện Thoại");

            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue("Email");

            cell = row.createCell(10, CellType.STRING);
            cell.setCellValue("Trạng Thái");

            cell = row.createCell(11, CellType.STRING);
            cell.setCellValue("Chức Vụ");

            cell = row.createCell(12, CellType.STRING);
            cell.setCellValue("Ngày Bắt Đầu");

            ArrayList<NhanVienModel> arr = (ArrayList<NhanVienModel>) showData.getAll();
            for (int j = 0; j < arr.size(); j++) {
                NhanVienModel item = arr.get(j);

                row = sheet.createRow(4 + j);
                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(j + 1);

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(arr.get(j).getMaNV());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(arr.get(j).getTaiKhoan());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(arr.get(j).getMatKhau());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(arr.get(j).getHoTen());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(arr.get(j).isGioiTinh());

                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(arr.get(j).getNgaySinh());

                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue(arr.get(j).getDiaChi());

                cell = row.createCell(8, CellType.STRING);
                cell.setCellValue(arr.get(j).getSDT());

                cell = row.createCell(9, CellType.STRING);
                cell.setCellValue(arr.get(j).getEmail());

                cell = row.createCell(10, CellType.STRING);
                cell.setCellValue(arr.get(j).getTrangThai());

                cell = row.createCell(11, CellType.STRING);
                cell.setCellValue(arr.get(j).getChucVu());

                cell = row.createCell(12, CellType.STRING);
                cell.setCellValue(arr.get(j).getNgayBatDau());
            }
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn nơi nhận tệp tin");

            fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

            int userSelection = fileChooser.showSaveDialog(null);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fillToSave = fileChooser.getSelectedFile();
                try (FileOutputStream fos = new FileOutputStream(fillToSave.getAbsolutePath() + ".xlsx")) {
                    wordbook.write(fos);
                    JOptionPane.showMessageDialog(null, "Đã lưu file Excel thành công.");
                } catch (IOException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Lỗi khi lưu file Excel.");
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi tạo file Excel.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TimKiemKeyReleased

        String khoa = TimKiem.getText().toLowerCase();

        ArrayList<NhanVienModel> s = this.rp.timKiem(khoa);

        DefaultTableModel dtm = (DefaultTableModel) tbl_bangNhanVien.getModel();
        dtm.setRowCount(0);

        for (NhanVienModel nhanVienModel : s) {
            dtm.addRow(new Object[]{
                nhanVienModel.getMaNV(),
                nhanVienModel.getTaiKhoan(),
                nhanVienModel.getMatKhau(),
                nhanVienModel.getHoTen(),
                nhanVienModel.isGioiTinh() ? "Nam" : "Nữ",
                nhanVienModel.getNgaySinh(),
                nhanVienModel.getDiaChi(),
                nhanVienModel.getSDT(),
                nhanVienModel.getEmail(),
                nhanVienModel.getTrangThai() == 0 ? "Đang Làm" : "Nghỉ Làm",
                nhanVienModel.getChucVu(),
                nhanVienModel.getNgayBatDau()
            });
        }


    }//GEN-LAST:event_TimKiemKeyReleased

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed

    }//GEN-LAST:event_TimKiemActionPerformed

    private void lbhinhAnh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbhinhAnh1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbhinhAnh1MouseClicked

    private void txt_taiKhoan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_taiKhoan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_taiKhoan1ActionPerformed

    private void btn_sua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sua2ActionPerformed
        // TODO add your handling code here:
        int i = tbl_bangNhanVien1.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng nào để khôi phục");
        } else {
            String ma = tbl_bangNhanVien1.getValueAt(i, 0).toString();
            if (rp.KhoiPhuc(ma) > 0) {
                JOptionPane.showMessageDialog(this, "Khôi phục nhân viên thành công");
                this.fillTable1(rp.getAll1());
                List<NhanVienModel> allNhanVien = rp.getAll();
                NhanVienModel nv = null;
                for (NhanVienModel nhanVien : allNhanVien) {
                    if (nhanVien.getMaNV().equals(ma)) {
                        nv = nhanVien;
                        break;
                    }
                }
                if (nv != null && nv.getTrangThai() == 0) {
                    this.fillTable(rp.getAll());
                } else {
                    this.fillTable1(rp.getAll1());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Khôi phục nhân viên thất bại");
            }
        }


    }//GEN-LAST:event_btn_sua2ActionPerformed


    private void cbo_gioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_gioiTinhActionPerformed

        filterNhanVien();
    }//GEN-LAST:event_cbo_gioiTinhActionPerformed

    private void cbo_CVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_CVActionPerformed
        // TODO add your handling code here:
        filterNhanVien();
    }//GEN-LAST:event_cbo_CVActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = tbl_bangNhanVien.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng nào để xoá!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá nhân viên này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        String maNV = tbl_bangNhanVien.getValueAt(i, 0).toString();
        if (rp.Xoa(maNV) > 0) {
            JOptionPane.showMessageDialog(this, "Nhân viên đã được chuyển sang trạng thái nghỉ làm");
            this.fillTable(rp.getAll());
        } else {
            JOptionPane.showMessageDialog(this, "Xoá thất bại");
        }
        fillTable1(rp.getAll1());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TimKiem;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_sua2;
    private javax.swing.JButton btn_them;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbo_CV;
    private javax.swing.JComboBox<String> cbo_chucVu;
    private javax.swing.JComboBox<String> cbo_chucVu1;
    private javax.swing.JComboBox<String> cbo_gioiTinh;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel lbhinhAnh;
    private javax.swing.JLabel lbhinhAnh1;
    private javax.swing.JRadioButton rdo_dangLam;
    private javax.swing.JRadioButton rdo_dangLam1;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nam1;
    private javax.swing.JRadioButton rdo_nghiLam;
    private javax.swing.JRadioButton rdo_nghiLam1;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JRadioButton rdo_nu1;
    private javax.swing.JTable tbl_bangNhanVien;
    private javax.swing.JTable tbl_bangNhanVien1;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_diaChi1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_hoTen1;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JTextField txt_maNV1;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JPasswordField txt_matKhau1;
    private com.toedter.calendar.JDateChooser txt_ngayBatDau;
    private com.toedter.calendar.JDateChooser txt_ngayBatDau1;
    private com.toedter.calendar.JDateChooser txt_ngaySinh;
    private com.toedter.calendar.JDateChooser txt_ngaySinh1;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_sdt1;
    private javax.swing.JTextField txt_taiKhoan;
    private javax.swing.JTextField txt_taiKhoan1;
    // End of variables declaration//GEN-END:variables
void showData() {
        int i = tbl_bangNhanVien.getSelectedRow();
        NhanVienModel x = rp.getAll().get(i);
        txt_maNV.setText(x.getMaNV());
        txt_hoTen.setText(x.getHoTen());
        txt_taiKhoan.setText(x.getTaiKhoan());
        txt_matKhau.setText(x.getMatKhau());
        txt_diaChi.setText(x.getDiaChi());
        txt_sdt.setText(x.getSDT());
        txt_email.setText(x.getEmail());
        rdo_nam.setSelected(x.isGioiTinh() ? true : false);
        rdo_nu.setSelected(x.isGioiTinh() ? false : true);
        txt_ngayBatDau.setDate(x.getNgayBatDau());
        txt_ngaySinh.setDate(x.getNgaySinh());
        String chucVuString = String.valueOf(x.getChucVu());
        cbo_chucVu.setSelectedItem(chucVuString);
        if (x.getTrangThai() == 0) {
            rdo_dangLam.setSelected(true);
            rdo_nghiLam.setSelected(false);
        } else {
            rdo_dangLam.setSelected(false);
            rdo_nghiLam.setSelected(true);
        }
        path = x.getHinhanh();
        ImageIcon img = new ImageIcon(path);
        lbhinhAnh.setIcon(img);
    }

    void showData1() {
        int i = tbl_bangNhanVien1.getSelectedRow();
        NhanVienModel x = rp.getAll1().get(i);
        txt_maNV1.setText(x.getMaNV());
        txt_hoTen1.setText(x.getHoTen());
        txt_taiKhoan1.setText(x.getTaiKhoan());
        txt_matKhau1.setText(x.getMatKhau());
        txt_diaChi1.setText(x.getDiaChi());
        txt_sdt1.setText(x.getSDT());
        txt_email1.setText(x.getEmail());
        rdo_nam1.setSelected(x.isGioiTinh() ? true : false);
        rdo_nu1.setSelected(x.isGioiTinh() ? false : true);
        txt_ngayBatDau1.setDate(x.getNgayBatDau());
        txt_ngaySinh1.setDate(x.getNgaySinh());
        String chucVuString = String.valueOf(x.getChucVu());
        cbo_chucVu1.setSelectedItem(chucVuString);
        if (x.getTrangThai() == 1) {
            rdo_dangLam1.setSelected(false);
            rdo_nghiLam1.setSelected(true);
        } else {
            rdo_dangLam1.setSelected(true);
            rdo_nghiLam1.setSelected(false);
        }
        path = x.getHinhanh();
        ImageIcon img = new ImageIcon(path);
        lbhinhAnh1.setIcon(img);
    }

    NhanVienModel readForm1() {
        NhanVienModel st = new NhanVienModel();

        st.setMaNV(txt_maNV.getText());
        st.setTaiKhoan(txt_taiKhoan.getText());
        st.setMatKhau(txt_matKhau.getText());
        st.setHoTen(txt_hoTen.getText());

        if (rdo_nam.isSelected()) {
            st.setGioiTinh(true);
        } else {
            st.setGioiTinh(false);
        }

        // Kiểm tra và xử lý ngày sinh
        Date ngaySinh = txt_ngaySinh.getDate();
        if (ngaySinh != null) {
            st.setNgaySinh(ngaySinh);
        }

        st.setDiaChi(txt_diaChi.getText());
        st.setSDT(txt_sdt.getText());
        st.setHinhanh(path);

        st.setEmail(txt_email.getText());
        if (rdo_dangLam.isSelected()) {
            st.setTrangThai(0);
        } else {
            st.setTrangThai(1);
        }

        st.setChucVu(cbo_chucVu.getSelectedItem().toString());
        st.setNgayBatDau(txt_ngayBatDau.getDate());

        return st;
    }

    public NhanVienModel readForm() {
        NhanVienModel st = new NhanVienModel();

//        // Kiểm tra Mã nhân viên
//        String maNV = txt_maNV.getText().trim();
//        if (maNV.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Mã nhân viên không được để trống!");
//            txt_maNV.requestFocus();
//            return null;
//        }
//        st.setMaNV(maNV);

        // Kiểm tra Tài khoản
        String taiKhoan = txt_taiKhoan.getText().trim();
        if (taiKhoan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tài khoản không được để trống!");
            txt_taiKhoan.requestFocus();
            return null;
        }
        if (taiKhoan.length() < 6 || taiKhoan.length() > 12) {
            JOptionPane.showMessageDialog(null, "Tài khoản phải có từ 6 đến 12 ký tự!");
            txt_taiKhoan.requestFocus();
            return null;
        }
        // Tài khoản chỉ chứa chữ cái
        String regexTaiKhoan = "^[A-Za-z][A-Za-z0-9]{5,11}$";
        if (!taiKhoan.matches(regexTaiKhoan)) {
            JOptionPane.showMessageDialog(null, "Tài khoản phải bắt đầu bằng chữ cái và có từ 6 đến 12 ký tự, có thể chứa số sau ký tự đầu tiên!");
            txt_taiKhoan.requestFocus();
            return null;
        }
        st.setTaiKhoan(taiKhoan);

        // Kiểm tra Mật khẩu
        String matKhau = txt_matKhau.getText().trim();
        if (matKhau.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mật khẩu không được để trống!");
            txt_matKhau.requestFocus();
            return null;
        }
        String regexMatKhau = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
        if (!matKhau.matches(regexMatKhau)) {
            JOptionPane.showMessageDialog(null, "Mật khẩu phải chứa ít nhất 1 chữ hoa, 1 chữ thường, 1 chữ số và 1 ký tự đặc biệt, và phải có ít nhất 8 ký tự!");
            txt_matKhau.requestFocus();
            return null;
        }
        st.setMatKhau(matKhau);

        // Kiểm tra Họ tên
        String hoTen = txt_hoTen.getText().trim();
        if (hoTen.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Họ tên không được để trống!");
            txt_hoTen.requestFocus();
            return null;
        }

        if (!hoTen.matches("[a-zA-ZÀ-ỹ ]+")) { 
            JOptionPane.showMessageDialog(null, "Họ tên không được chứa số hoặc ký tự đặc biệt!");
            txt_hoTen.requestFocus();
            return null;
        }

        st.setHoTen(hoTen);


        // Kiểm tra Giới tính
        if (rdo_nam.isSelected()) {
            st.setGioiTinh(true);  // Nam
        } else if (rdo_nu.isSelected()) {
            st.setGioiTinh(false);  // Nữ
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn giới tính!");
            rdo_nam.requestFocus();
            return null;
        }

        // Xử lý ngày sinh
        Date ngaySinh = txt_ngaySinh.getDate();
        if (ngaySinh != null) {
            Calendar calendar = Calendar.getInstance();
            int currentYear = calendar.get(Calendar.YEAR);

            Calendar birthday = Calendar.getInstance();
            birthday.setTime(ngaySinh);
            int age = currentYear - birthday.get(Calendar.YEAR);

            if (age < 15 || age > 61) {
                JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ! Bạn phải từ 15 đến 61 tuổi.");
                txt_ngaySinh.requestFocus();
                return null;
            }
            st.setNgaySinh(ngaySinh);
        } else {
            JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ!");
            txt_ngaySinh.requestFocus();
            return null;
        }

        // Kiểm tra Địa chỉ
        String diaChi = txt_diaChi.getText().trim();
        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống!");
            txt_diaChi.requestFocus();
            return null;
        }
        st.setDiaChi(diaChi);

        // Kiểm tra Số điện thoại
        String sdt = txt_sdt.getText().trim();
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không được để trống!");
            txt_sdt.requestFocus();
            return null;
        }
        if (!Pattern.matches("^\\d{10}$", sdt)) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ! Vui lòng nhập đúng định dạng (10 chữ số).");
            txt_sdt.requestFocus();
            return null;
        }
        st.setSDT(sdt);

        // Kiểm tra Email
        String email = txt_email.getText().trim();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email không được để trống!");
            txt_email.requestFocus();
            return null;
        }
        String regexEmail = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if (!email.matches(regexEmail)) {
            JOptionPane.showMessageDialog(null, "Email không hợp lệ!");
            txt_email.requestFocus();
            return null;
        }
        st.setEmail(email);

        // Hình ảnh
        st.setHinhanh(path);

        // Kiểm tra trạng thái làm việc
        if (rdo_dangLam.isSelected()) {
            st.setTrangThai(0);  // Đang làm
        } else if (rdo_nghiLam.isSelected()) {
            st.setTrangThai(1);  // Nghỉ làm
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn trạng thái!");
            rdo_dangLam.requestFocus();
            return null;
        }

        // Kiểm tra Chức vụ
        String chucVu = cbo_chucVu.getSelectedItem().toString();
        if (chucVu.equals("Chọn chức vụ")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn chức vụ!");
            cbo_chucVu.requestFocus();
            return null;
        }
        st.setChucVu(chucVu);

        // Kiểm tra Ngày bắt đầu
        Date ngayBatDau = txt_ngayBatDau.getDate();
        if (ngayBatDau != null) {
            if (ngayBatDau.after(new Date())) {
                JOptionPane.showMessageDialog(null, "Ngày bắt đầu không được lớn hơn ngày hiện tại!");
                txt_ngayBatDau.requestFocus();
                return null;
            }
            st.setNgayBatDau(ngayBatDau);
        } else {
            JOptionPane.showMessageDialog(null, "Ngày bắt đầu không hợp lệ!");
            txt_ngayBatDau.requestFocus();
            return null;
        }

        return st;
    }

    private void filterNhanVien() {
        String selectedGioiTinh = (String) cbo_gioiTinh.getSelectedItem();
        String selectedChucVu = (String) cbo_CV.getSelectedItem();
        boolean filterByGioiTinh = false;
        boolean gioiTinhValue = true; // Mặc định là Nam
        boolean filterByChucVu = false;
        String chucVuValue = "";
        if (selectedGioiTinh != null && !selectedGioiTinh.equalsIgnoreCase("Tất Cả")) {
            filterByGioiTinh = true;
            if (selectedGioiTinh.equalsIgnoreCase("Nam")) {
                gioiTinhValue = true;
            } else if (selectedGioiTinh.equalsIgnoreCase("Nữ")) {
                gioiTinhValue = false;
            }
        }
        if (selectedChucVu != null && !selectedChucVu.equalsIgnoreCase("Tất Cả")) {
            filterByChucVu = true;
            chucVuValue = selectedChucVu;
        }
        try {
            List<NhanVienModel> list;
            if (filterByGioiTinh && filterByChucVu) {
                // Lọc theo giới tính và chức vụ
                list = rp.LocGioiTinhVaChucVu(gioiTinhValue, chucVuValue);
            } else if (filterByGioiTinh) {
                // Lọc chỉ theo giới tính
                list = rp.LocGioiTinh(gioiTinhValue);
            } else if (filterByChucVu) {
                // Lọc chỉ theo chức vụ
                list = rp.LocChucVu(chucVuValue);
            } else {
                list = rp.getAll();
            }

            fillTable(new ArrayList<>(list));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lọc dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    List<NhanVienModel> listNhanVien = rp.getAll();

    public boolean checkTrung(NhanVienModel nv) {
        for (NhanVienModel nhanVien : listNhanVien) {
            if (nhanVien.getMaNV().trim().equals(nv.getMaNV().trim())) {
                JOptionPane.showMessageDialog(null, "Mã nhân viên đã tồn tại!");
                txt_maNV.requestFocus();
                return true;
            }
            if (nhanVien.getEmail().trim().equals(nv.getEmail().trim())) {
                JOptionPane.showMessageDialog(null, "Email đã tồn tại!");
                txt_email.requestFocus();
                return true;
            }
            if (nhanVien.getTaiKhoan().trim().equals(nv.getTaiKhoan().trim())) {
                JOptionPane.showMessageDialog(null, "Tài khoản đã tồn tại!");
                txt_taiKhoan.requestFocus();
                return true;
            }
            if (nhanVien.getSDT().trim().equals(nv.getSDT().trim())) {
                JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại!");
                txt_sdt.requestFocus();
                return true;
            }
        }
        return false;
    }

    public boolean checkTrungKhiSua(NhanVienModel nv, String maHienTai) {
        for (NhanVienModel nhanVien : listNhanVien) {
            if (nhanVien.getMaNV().equals(maHienTai)) {
                continue;
            }
            if (nhanVien.getEmail().trim().equals(nv.getEmail().trim())) {
                JOptionPane.showMessageDialog(null, "Email đã tồn tại!");
                txt_email.requestFocus();
                return true;
            }
            if (nhanVien.getTaiKhoan().trim().equals(nv.getTaiKhoan().trim())) {
                JOptionPane.showMessageDialog(null, "Tài khoản đã tồn tại!");
                txt_taiKhoan.requestFocus();
                return true;
            }
            if (nhanVien.getSDT().trim().equals(nv.getSDT().trim())) {
                JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại!");
                txt_sdt.requestFocus();
                return true;
            }
        }
        return false;
    }

}
